name: Deploy docs

on: 
  push:
    paths: ["apps/docs/**"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm ci

      - name: Deploy storybook to GitHub Pages
        working-directory: ./apps/docs
        run: npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}